name: AxtonsEmotes
version: '${project.version}'
main: arizonsoftware.axtonsemotes.AxtonsEmotes
api-version: '1.20'

commands:
   hug:
     aliases: [cuddle]
   kiss:
     aliases: [smooch]
   poke:
     aliases: [prod]
   highfive:
     aliases: [brofist, hf]
   slap:
     aliases: [hit]
   thank:
     aliases: [appreciate]
   lick:
     aliases: []