name: AxtonsEmotes
version: '${version}'
main: com.arizonsoftware.AxtonsEmotes
api-version: '1.21'

commands:
  hug:
    description: Hug another player.
    aliases: [cuddle]
  kiss:
    description: Kiss another player.
    aliases: [smooch]
  poke:
    description: Poke another player.
  highfive:
    description: High-five another player.
    aliases: [hf]
  thank:
    description: Thank another player.
    aliases: [ty]
  slap:
    description: Slap another player.

  cry:
    description: Express your sadness to the server.