name: AxtonsEmotes
version: '${project.version}'
main: arizonsoftware.axtonsemotes.AxtonsEmotes
api-version: '1.20'

commands:
  hug:
    description: Hug another player
    aliases: [cuddle]
  kiss:
    description: Kiss another player
    aliases: [smooch]
  poke:
    description: Poke another player
    aliases: []
  highfive:
    description: High-five another player
    aliases: [hf]
  slap:
    description: Slap another player
    aliases: [hit]
  lick:
    description: Lick another player
    aliases: []