name: AxtonsEmotes
version: '${version}'
main: com.arizonsoftware.Main
author: axtonprice
website: https://github.com/axtonprice/axtons-emotes
description: A simple social emotes & expression chat plugin for Minecraft servers.
api-version: '1.21'

commands:

  # Misc commands
  axtonsemotes:
    description: Main plugin command
    aliases: [ae]
  emotes:
    description: Displays available emote commands
    aliases: []
  expressions:
    description: Displays available expression commands
    aliases: []
  bog:
    description: Jumpscares the player with bogged entities
    aliases: []

  # Emotes
  hug:
    description: Hug another player.
    aliases: [cuddle]
  kiss:
    description: Kiss another player.
    aliases: [smooch]
  poke:
    description: Poke another player.
  highfive:
    description: High-five another player.
    aliases: [hf]
  thank:
    description: Thank another player.
    aliases: [ty]
  slap:
    description: Slap another player.
  dapup:
      description: Dap-up another player.
      aliases: [dap]
  stomp:
    description: Stomp on another player's foot.
    aliases: []
  stab:
    description: Stab another player
    aliases: [ shank ]
  stare:
    description: Stare at another player

  # Expressions
  wave:
    description: Say hello to everyone! (Public)
  cry:
    aliases: [ sulk ]
    description: Express your sadness. (Public)
  applaud:
    description: Applaud another player. (Public)
    aliases: [ clap ]

# Command permissions
permissions:
  axtonsemotes.reload:
    default: op