name: AxtonsEmotes
version: '${project.version}'
main: arizonsoftware.axtonsemotes.AxtonsEmotes
api-version: '1.20'

commands:
   hug:
     aliases: []
   kiss:
     aliases: []
   poke:
     aliases: []
   highfive:
     aliases: []
   slap:
     aliases: []
   thank:
     aliases: []
   lick:
     aliases: []