name: AxtonsEmotes
version: '1.0-SNAPSHOT'
main: arizonsoftware.axtonsemotes.AxtonsEmotes
api-version: '1.20'

commands:
   hug:
     aliases: []
   kiss:
     aliases: []
   poke:
     aliases: []
   highfive:
     aliases: []
   slap:
     aliases: []
   thank:
     aliases: []
   lick:
     aliases: []