name: AxtonsEmotes
version: '${version}'
main: com.arizonsoftware.Main
api-version: '1.21'

commands:

  # Misc commands
  axtonsemotes:
    description: Main plugin command
    aliases: []
  emotes:
    description: Displays available emote commands
    aliases: []
  expressions:
    description: Displays available expression commands
    aliases: []

  # Emotes
  hug:
    description: Hug another player.
    aliases: [cuddle]
  kiss:
    description: Kiss another player.
    aliases: [smooch]
  poke:
    description: Poke another player.
  highfive:
    description: High-five another player.
    aliases: [hf]
  thank:
    description: Thank another player.
    aliases: [ty]
  slap:
    description: Slap another player.
  dap:
      description: Dap-up another player.
      aliases: [dapup]
  stomp:
    description: Stomp another player's foot.
    aliases: [shinkick]
  stab:
    description: Stab another player
    aliases: [ shank ]
  stare:
    description: Stare at another player
    aliases: [  ]

  # Expressions
  cry:
    description: Cry in sadness.
  sulk:
    description: Sulk in your sadness.
  applaud:
    description: Publicly applaud another player.
    aliases: [ clap, cheer ]


permissions:
  axtonsemotes.reload:
    default: op